### PR TITLE
Migrate to xproj/project.json and add support for .NET Standard v1.5

### PR DESCRIPTION
**Pull request by jeremymeng**

### CODE REVIEW

**Comment by nblumhardt** [comment]
LGTM! Thanks @jeremymeng.

@mivano shall we :shipit:?

(Just spotted http://stackoverflow.com/questions/39164167/serilog-loggly-csharp-fullnetfx/39197969#39197969)

**Comment by jeremymeng** [comment]
Thanks! However, configuration via app.config are not supported on the netstandard port though since the Api's are not available in .NET Core.

**Comment by mivano** [comment]
Sorry, I did not had time yet to go through this in detail and will be away for some weeks. So if all tested I would say yes, do ship it. But also do check if the right frameworks are targeted. I made some changes in the PR that @jeremymeng did for serilog metrics regarding the target frameworks.

**Comment by jeremymeng** [comment]
> I made some changes in the PR that @jeremymeng did for serilog metrics regarding the target frameworks.

For Serilog Metrics I had net45 and netstandard1.1 for the library.  I tried to get the supported netstandard version as low as possible to support more platforms.  I used net451 for the test project because dotnet-test-nunit doesn't support net45.

**Comment by jeremymeng** [comment]
Anything I can do to move this PR forward?  Thanks!

**Comment by mivano** [comment]
Sorry I'm in the middle of a house move so I have limited internet.
@nblumhardt: can you check and merge?

Op do 15 sep. 2016 om 19:04 schreef Jeremy Meng <notifications@github.com>

**Comment by nblumhardt** [comment]
:boom: :-)

**Comment by jeremymeng** [comment]
Thank you!

**Pull request merged**
