### PR TITLE
migrated the obsolete xproj to the new csproj and updated nuget packages

### PR DESCRIPTION
**Pull request by tamirdresher**
Migrated the obsolete xproj to the new csproj (https://docs.microsoft…com/en-us/dotnet/core/migration/).

Updated nuget packages ( #21 ):
- loggly-csharp 4.6.0.5 --> 4.6.1.45
- Newtonsoft.Json 9.0.1 --> 10.0.3
- Serilog 2.0.0 --> 2.5.0
- Serilog.Sinks.PeriodicBatching 2.0.0 --> 2.1.1
- Serilog.Sinks.File 3.1.1 --> 3.2.0
- Serilog.Sinks.RollingFile 3.2.0 --> 3.3.0
- Serilog.Sinks.RollingFileAlternate 2.0.6 --> 2.0.9 
- Serilog.Sinks.Async 1.0.1 --> 1.1.0 
- Serilog.Enrichers.Environment 2.1.1 --> 2.1.2 
- Serilog.Enrichers.Process 2.0.0 --> 2.0.1

### CODE REVIEW

**Comment by nblumhardt** [comment]
Great 👍 

Issue with the build:

```
Collecting artifacts...
No artifacts found matching 'artifacts\Serilog.*.nupkg' path
Build success
```

The Serilog projects all generally use the same standardized `Build.ps1` file - grabbing e.g. https://github.com/serilog/serilog-sinks-console/blob/dev/Build.ps1 and copying it in directly should fix this.

**Comment by tamirdresher** [comment]
@nblumhardt
I reverted the Build.ps1 back to what it was. But i had to change the appveyor.yml in order to use the VS2017 image.
Everything works the same as it was now.

**Comment by nblumhardt** [comment]
@tamirdresher awesome, merged!

I am going to bump the dev package version to 5.1 to reflect some change going on under the hood.

**Comment by tamirdresher** [comment]
Thanks @nblumhardt
I'm happy that i could help.
Looking forward to use the new package

**Pull request merged**
